name: sip_calculator
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'
dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  google_fonts: ^4.0.1
  get: ^4.6.5
  fluttertoast: ^8.1.2
  share_plus: ^6.3.0
  animated_splash_screen: ^1.3.0
  syncfusion_flutter_sliders: ^20.4.49
  syncfusion_flutter_gauges: ^20.4.49
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  intl: ^0.18.0


flutter:

  uses-material-design: true

  assets:
    - assets/images/one.png
    - assets/images/coin.png
    - assets/images/doller.png
    - assets/images/hand.png
    - assets/images/ruppe.png
    - assets/images/stock.png
    
    
    
   
  

